apiVersion: batch/v1
kind: Job
metadata: 
    name: "{{ include "helm-hooks.fullname" . }}-backup-db"
    labels:
        {{- include "helm-hooks.labels" . | nindent 8}}
    annotations:
        "helm.sh/hook": pre-upgrade, pre-delete,pre-rollback
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
    backoffLimit: 2
    template:
        metadata:
            labels:
                {{- include "helm-hooks.labels" . | nindent 16 }}
        spec:
            restartPolicy: Never
            containers:
                - name: dummy-backup-db
                  image: "alpine:3.20.3"
                  command: ["sh", "-c", "echo 'Backing up some data'"]