# For test, not recommended
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "accessing-files.fullname" . }}
    type: Opaque
data:
{{ (.Files.Glob "files/*.properties").AsSecrets | indent 4}}
