{{- range $key, $svc := (.Values.services | default dict)}}
---
apiVersion: v1
kind: Service
metadata:
    name: {{  include "templating-deep-dive.fullName" $ }}-svc-{{ $key }}
    labels: {{ include "templating-deep-dive.selectorLabels" $ | nindent 8 }}
spec:
    type: {{ .type }}
    selector: {{ include "templating-deep-dive.selectorLabels" $ | nindent 8 }}
    ports:
        - protocol: TCP
          port: {{ .port }}
          targetPort: {{ $.Values.containerPorts.http }}
{{- end }}