{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
    name: {{  include "templating-deep-dive.fullName" .}}-svc
    labels: {{ include "templating-deep-dive.selectorLabels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    selector: {{ include "templating-deep-dive.selectorLabels" . | nindent 8 }}
    ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.containerPorts.http }}
{{ end }}