{{- range $idx, $svc := (.Values.services | default list)}}
---
apiVersion: v1
kind: Service
metadata:
    name: {{  include "templating-deep-dive.fullName" $ }}-svc-{{ $idx }}
    labels: {{ include "templating-deep-dive.selectorLabels" $ | nindent 8 }}
spec:
    type: {{ $svc.type }}
    selector: {{ include "templating-deep-dive.selectorLabels" $ | nindent 8 }}
    ports:
        - protocol: TCP
          port: {{ $svc.port }}
          targetPort: {{ $.Values.containerPorts.http }}
{{- end }}