test: I am a string
environment: production

## @param replicaCount Number of nginx replicas to deploy
replicaCount: 3

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: "1.27.0"

## NGINX container ports
##
## @param containerPorts.http
containerPorts:
  http: 80