test: I am a string
environment: production

## @param customName allows set a custom resource name for the Kubernetes resourses
## Defaults to {{ .Release.Name }}-{{.Chart.Name}}
customName: ''

## @param replicaCount Number of nginx replicas to deploy
replicaCount: 3

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: "1.27.0"

## Settings for NGINX security context
##
## @param securityContext.enabled
## @param securityContext.runAsUser 
## @param securityContext.fsGroup 
securityContext:
  enabled: false
  runAsUser: 1000
  fsGroup: 2000

## NGINX container ports
##
## @param containerPorts.http
containerPorts:
  http: 80

## Settings for Nginx Services
## services is a map with the following schema
##
## @param services["*"].type The type of service in front of the Nginx pods
## @param service["*"].port The port where the service is receiving requests
services:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007